-- params : ...
-- function num : 0 , upvalues : _ENV
require("CommonResource_BlackBgAniBByName")
require("CommonResource_ResultImageByName")
require("CommonResource_ResultDiamondLeftByName")
require("CommonResource_ResultDiamondRightByName")
require("Card_AttributeUpByName")
GetCard_StarUpPropertyUis = function(ui, ...)
  -- function num : 0_0 , upvalues : _ENV
  local uis = {}
  uis.BlackBgAni = GetCommonResource_BlackBgAniBUis(ui:GetChild("BlackBgAni"))
  uis.RedImage = ui:GetChild("RedImage")
  uis.ResultImageGrp = GetCommonResource_ResultImageUis(ui:GetChild("ResultImageGrp"))
  uis.ResultDiamondLeft = GetCommonResource_ResultDiamondLeftUis(ui:GetChild("ResultDiamondLeft"))
  uis.ResultDiamondRight = GetCommonResource_ResultDiamondRightUis(ui:GetChild("ResultDiamondRight"))
  uis.Decorate_11_Image = ui:GetChild("Decorate_11_Image")
  uis.Decorate_12_Image = ui:GetChild("Decorate_12_Image")
  uis.TipsTxt = ui:GetChild("TipsTxt")
  uis.StarList = ui:GetChild("StarList")
  uis.PowerWordTxt = ui:GetChild("PowerWordTxt")
  uis.PowerNumberTxt = ui:GetChild("PowerNumberTxt")
  uis.AttributeUp = GetCard_AttributeUpUis(ui:GetChild("AttributeUp"))
  uis.ATK_02_Image = ui:GetChild("ATK_02_Image")
  uis.ATKTxt = ui:GetChild("ATKTxt")
  uis.ATKNumber_01_Txt = ui:GetChild("ATKNumber_01_Txt")
  uis.ATKNumber_02_Txt = ui:GetChild("ATKNumber_02_Txt")
  uis.ATKGrp = ui:GetChild("ATKGrp")
  uis.AttributeUp = GetCard_AttributeUpUis(ui:GetChild("AttributeUp"))
  uis.DEF_02_Image = ui:GetChild("DEF_02_Image")
  uis.DEFTxt = ui:GetChild("DEFTxt")
  uis.DEFNumber_01_Txt = ui:GetChild("DEFNumber_01_Txt")
  uis.DEFNumber_02_Txt = ui:GetChild("DEFNumber_02_Txt")
  uis.DEFGrp = ui:GetChild("DEFGrp")
  uis.AttributeUp = GetCard_AttributeUpUis(ui:GetChild("AttributeUp"))
  uis.HP_02_Image = ui:GetChild("HP_02_Image")
  uis.HPTxt = ui:GetChild("HPTxt")
  uis.HPNumber_01_Txt = ui:GetChild("HPNumber_01_Txt")
  uis.HPNumber_02_Txt = ui:GetChild("HPNumber_02_Txt")
  uis.HPGrp = ui:GetChild("HPGrp")
  uis.AttributeUp = GetCard_AttributeUpUis(ui:GetChild("AttributeUp"))
  uis.CRT_02_Image = ui:GetChild("CRT_02_Image")
  uis.CRTTxt = ui:GetChild("CRTTxt")
  uis.CRTNumber_01_Txt = ui:GetChild("CRTNumber_01_Txt")
  uis.CRTNumber_02_Txt = ui:GetChild("CRTNumber_02_Txt")
  uis.CRTGrp = ui:GetChild("CRTGrp")
  uis.AttributeUp = GetCard_AttributeUpUis(ui:GetChild("AttributeUp"))
  uis.REC_02_Image = ui:GetChild("REC_02_Image")
  uis.RECTxt = ui:GetChild("RECTxt")
  uis.RECNumber_01_Txt = ui:GetChild("RECNumber_01_Txt")
  uis.RECNumber_02_Txt = ui:GetChild("RECNumber_02_Txt")
  uis.RECGrp = ui:GetChild("RECGrp")
  uis.AttributeUp = GetCard_AttributeUpUis(ui:GetChild("AttributeUp"))
  uis.BLK_02_Image = ui:GetChild("BLK_02_Image")
  uis.BLKTxt = ui:GetChild("BLKTxt")
  uis.BLKNumber_01_Txt = ui:GetChild("BLKNumber_01_Txt")
  uis.BLKNumber_02_Txt = ui:GetChild("BLKNumber_02_Txt")
  uis.BLKGrp = ui:GetChild("BLKGrp")
  uis.AttributeUp = GetCard_AttributeUpUis(ui:GetChild("AttributeUp"))
  uis.REB_02_Image = ui:GetChild("REB_02_Image")
  uis.REBTxt = ui:GetChild("REBTxt")
  uis.REBNumber_01_Txt = ui:GetChild("REBNumber_01_Txt")
  uis.REBNumber_02_Txt = ui:GetChild("REBNumber_02_Txt")
  uis.REBGrp = ui:GetChild("REBGrp")
  uis.ALLTxt = ui:GetChild("ALLTxt")
  uis.ALLNumber_01_Txt = ui:GetChild("ALLNumber_01_Txt")
  uis.AllGrp = ui:GetChild("AllGrp")
  uis.TouchScreenBtn = ui:GetChild("TouchScreenBtn")
  uis.StageUpPropertyGrp = ui:GetChild("StageUpPropertyGrp")
  uis.root = ui
  return uis
end


