-- params : ...
-- function num : 0 , upvalues : _ENV
require("Card_ContentAttributeByName")
GetCard_DetailedContentPropertyUis = function(ui, ...)
  -- function num : 0_0 , upvalues : _ENV
  local uis = {}
  uis.Decorate_02_Image = ui:GetChild("Decorate_02_Image")
  uis.Decorate_02_Image = ui:GetChild("Decorate_02_Image")
  uis.Decorate_01_Image = ui:GetChild("Decorate_01_Image")
  uis.ShuXingNameTxt = ui:GetChild("ShuXingNameTxt")
  uis.n199 = GetCard_ContentAttributeUis(ui:GetChild("n199"))
  uis.SMNameTxt = ui:GetChild("SMNameTxt")
  uis.SMNumberTxt = ui:GetChild("SMNumberTxt")
  uis.ShengMingGrp = ui:GetChild("ShengMingGrp")
  uis.n200 = GetCard_ContentAttributeUis(ui:GetChild("n200"))
  uis.GJNameTxt = ui:GetChild("GJNameTxt")
  uis.GJNumberTxt = ui:GetChild("GJNumberTxt")
  uis.GongJiGrp = ui:GetChild("GongJiGrp")
  uis.n201 = GetCard_ContentAttributeUis(ui:GetChild("n201"))
  uis.FYNameTxt = ui:GetChild("FYNameTxt")
  uis.FYNumberTxt = ui:GetChild("FYNumberTxt")
  uis.FangYuGrp = ui:GetChild("FangYuGrp")
  uis.n202 = GetCard_ContentAttributeUis(ui:GetChild("n202"))
  uis.SDNameTxt = ui:GetChild("SDNameTxt")
  uis.SDNumberTxt = ui:GetChild("SDNumberTxt")
  uis.SuDuGrp = ui:GetChild("SuDuGrp")
  uis.n203 = GetCard_ContentAttributeUis(ui:GetChild("n203"))
  uis.XYNameTxt = ui:GetChild("XYNameTxt")
  uis.XYNumberTxt = ui:GetChild("XYNumberTxt")
  uis.XingYunGrp = ui:GetChild("XingYunGrp")
  uis.n204 = GetCard_ContentAttributeUis(ui:GetChild("n204"))
  uis.BJNameTxt = ui:GetChild("BJNameTxt")
  uis.BJNumberTxt = ui:GetChild("BJNumberTxt")
  uis.BaoJiGrp = ui:GetChild("BaoJiGrp")
  uis.n205 = GetCard_ContentAttributeUis(ui:GetChild("n205"))
  uis.KBNameTxt = ui:GetChild("KBNameTxt")
  uis.KBNumberTxt = ui:GetChild("KBNumberTxt")
  uis.KangBaoGrp = ui:GetChild("KangBaoGrp")
  uis.n206 = GetCard_ContentAttributeUis(ui:GetChild("n206"))
  uis.GDNameTxt = ui:GetChild("GDNameTxt")
  uis.GDNumberTxt = ui:GetChild("GDNumberTxt")
  uis.GeDangGrp = ui:GetChild("GeDangGrp")
  uis.n207 = GetCard_ContentAttributeUis(ui:GetChild("n207"))
  uis.PDNameTxt = ui:GetChild("PDNameTxt")
  uis.PDNumberTxt = ui:GetChild("PDNumberTxt")
  uis.PoJiGrp = ui:GetChild("PoJiGrp")
  uis.n208 = GetCard_ContentAttributeUis(ui:GetChild("n208"))
  uis.BJQDNameTxt = ui:GetChild("BJQDNameTxt")
  uis.BJQDNumberTxt = ui:GetChild("BJQDNumberTxt")
  uis.BaoJiQiangDuGrp = ui:GetChild("BaoJiQiangDuGrp")
  uis.n209 = GetCard_ContentAttributeUis(ui:GetChild("n209"))
  uis.KBQDNameTxt = ui:GetChild("KBQDNameTxt")
  uis.KBQDNumberTxt = ui:GetChild("KBQDNumberTxt")
  uis.KangBaoQiangDuGrp = ui:GetChild("KangBaoQiangDuGrp")
  uis.n210 = GetCard_ContentAttributeUis(ui:GetChild("n210"))
  uis.GDQDNameTxt = ui:GetChild("GDQDNameTxt")
  uis.GDQDNumberTxt = ui:GetChild("GDQDNumberTxt")
  uis.GeDangQiangDuGrp = ui:GetChild("GeDangQiangDuGrp")
  uis.n211 = GetCard_ContentAttributeUis(ui:GetChild("n211"))
  uis.PJQDTxt = ui:GetChild("PJQDTxt")
  uis.PJQDNumberTxt = ui:GetChild("PJQDNumberTxt")
  uis.PoJiQiangDuGrp = ui:GetChild("PoJiQiangDuGrp")
  uis.n212 = GetCard_ContentAttributeUis(ui:GetChild("n212"))
  uis.ZSQDNameTxt = ui:GetChild("ZSQDNameTxt")
  uis.ZSQDNumberTxt = ui:GetChild("ZSQDNumberTxt")
  uis.ZengShangQiangDuGrp = ui:GetChild("ZengShangQiangDuGrp")
  uis.n213 = GetCard_ContentAttributeUis(ui:GetChild("n213"))
  uis.MSQDNameTxt = ui:GetChild("MSQDNameTxt")
  uis.MSQDNumberTxt = ui:GetChild("MSQDNumberTxt")
  uis.MianShangQiangDuGrp = ui:GetChild("MianShangQiangDuGrp")
  uis.root = ui
  return uis
end


