-- params : ...
-- function num : 0 , upvalues : _ENV
require("Formation_CardOperationByName")
require("CommonResource_AssetStripByName")
require("Formation_ModelTemplateByName")
require("Formation_HeadListGrpByName")
require("Formation_FormationTipsByName")
GetFormation_FormationWindowUis = function(ui, ...)
  -- function num : 0_0 , upvalues : _ENV
  local uis = {}
  uis.CardOperationGrp2 = GetFormation_CardOperationUis(ui:GetChild("CardOperationGrp2"))
  uis.AssetStripGrp = GetCommonResource_AssetStripUis(ui:GetChild("AssetStripGrp"))
  uis.Self_01_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Self_01_Grp"))
  uis.Self_04_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Self_04_Grp"))
  uis.Self_02_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Self_02_Grp"))
  uis.Self_05_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Self_05_Grp"))
  uis.Self_03_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Self_03_Grp"))
  uis.Self_06_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Self_06_Grp"))
  uis.OneSelfGrp = ui:GetChild("OneSelfGrp")
  uis.Enemy_00_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Enemy_00_Grp"))
  uis.Enemy_03_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Enemy_03_Grp"))
  uis.Enemy_01_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Enemy_01_Grp"))
  uis.Enemy_04_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Enemy_04_Grp"))
  uis.Enemy_02_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Enemy_02_Grp"))
  uis.Enemy_05_Grp = GetFormation_ModelTemplateUis(ui:GetChild("Enemy_05_Grp"))
  uis.OneEnemyGrp = ui:GetChild("OneEnemyGrp")
  uis.VsImage = ui:GetChild("VsImage")
  uis.VsGrp = ui:GetChild("VsGrp")
  uis.ExpeditionBuffLoader = ui:GetChild("ExpeditionBuffLoader")
  uis.ExpeditionBuffNameTxt = ui:GetChild("ExpeditionBuffNameTxt")
  uis.ExpeditionGrp = ui:GetChild("ExpeditionGrp")
  uis.Battlepower_01_Txt = ui:GetChild("Battlepower_01_Txt")
  uis.BattleNumber_01_Txt = ui:GetChild("BattleNumber_01_Txt")
  uis.Number_01_Txt = ui:GetChild("Number_01_Txt")
  uis.MyselfGrp = ui:GetChild("MyselfGrp")
  uis.Battlepower_02_Txt = ui:GetChild("Battlepower_02_Txt")
  uis.BattleNumber_02_Txt = ui:GetChild("BattleNumber_02_Txt")
  uis.Number_02_Txt = ui:GetChild("Number_02_Txt")
  uis.EnemyGrp = ui:GetChild("EnemyGrp")
  uis.HeadListGrp = GetFormation_HeadListGrpUis(ui:GetChild("HeadListGrp"))
  uis.HeadGrp = ui:GetChild("HeadGrp")
  uis.ArenaSelf_01_Grp = GetFormation_ModelTemplateUis(ui:GetChild("ArenaSelf_01_Grp"))
  uis.ArenaSelf_04_Grp = GetFormation_ModelTemplateUis(ui:GetChild("ArenaSelf_04_Grp"))
  uis.ArenaSelf_02_Grp = GetFormation_ModelTemplateUis(ui:GetChild("ArenaSelf_02_Grp"))
  uis.ArenaSelf_05_Grp = GetFormation_ModelTemplateUis(ui:GetChild("ArenaSelf_05_Grp"))
  uis.ArenaSelf_03_Grp = GetFormation_ModelTemplateUis(ui:GetChild("ArenaSelf_03_Grp"))
  uis.ArenaSelf_06_Grp = GetFormation_ModelTemplateUis(ui:GetChild("ArenaSelf_06_Grp"))
  uis.ArenaOneSelfGrp = ui:GetChild("ArenaOneSelfGrp")
  uis.ArenaZudangback_01_Image = ui:GetChild("ArenaZudangback_01_Image")
  uis.ArenaNumber_01_Txt = ui:GetChild("ArenaNumber_01_Txt")
  uis.ArenaNumber_02_Txt = ui:GetChild("ArenaNumber_02_Txt")
  uis.ArenaMyselfGrp = ui:GetChild("ArenaMyselfGrp")
  uis.ArenaGrp = ui:GetChild("ArenaGrp")
  uis.BuffLoader = ui:GetChild("BuffLoader")
  uis.BuffNameTxt = ui:GetChild("BuffNameTxt")
  uis.Tower_01_Txt = ui:GetChild("Tower_01_Txt")
  uis.Tower_02_Txt = ui:GetChild("Tower_02_Txt")
  uis.RedImage = ui:GetChild("RedImage")
  uis.GreenImage = ui:GetChild("GreenImage")
  uis.TowerGrp = ui:GetChild("TowerGrp")
  uis.Decorate_04_Image = ui:GetChild("Decorate_04_Image")
  uis.Decorate_05_Image = ui:GetChild("Decorate_05_Image")
  uis.TipsTxt = ui:GetChild("TipsTxt")
  uis.FormationTipsGrp = GetFormation_FormationTipsUis(ui:GetChild("FormationTipsGrp"))
  uis.ExtBtn = ui:GetChild("ExtBtn")
  uis.c1Ctr = ui:GetController("c1")
  uis.root = ui
  return uis
end


